package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/urfave/cli/v2"
	"google.golang.org/api/calendar/v3"
)

const (
	defaultBackDays    = 720
	defaultForwardDays = 365
	primaryCalendarID  = "primary"
	orgHeader          = `
* Google Calendar: primary
These entries have been automatically generated, do not edit this file!
`
	dateLayout        = "2006-01-02 Mon"
	timeLayout        = "15:04"
	roomDisplayPrefix = "SYD 363 George St-"
)

func generateCommand() *cli.Command {
	return &cli.Command{
		Name:      "generate",
		Usage:     "generate an org file from Google Calendar",
		ArgsUsage: "FILE",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "backDays",
				Value: defaultBackDays,
				Usage: "How many days back to process events",
			},
			&cli.IntFlag{
				Name:  "forwardDays",
				Value: defaultForwardDays,
				Usage: "How many days forward to process events",
			},
		},
		Action: func(c *cli.Context) error {
			if c.NArg() != 1 {
				return cli.ShowCommandHelp(c, "generate")
			}
			outputPath := c.Args().First()
			backDays := c.Int("backDays")
			forwardDays := c.Int("forwardDays")

			ctx := context.Background()
			svc, err := newCalendarService(ctx, c.String("store"))
			if err != nil {
				return err
			}

			now := time.Now()
			return writeOutputFile(outputPath, func(w io.Writer) error {
				if _, err := io.WriteString(w, orgHeader); err != nil {
					return err
				}
				return writeEvents(w, svc, now, backDays, forwardDays)
			})
		},
	}
}

func writeOutputFile(path string, write func(io.Writer) error) (err error) {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := f.Close(); err == nil && closeErr != nil {
			err = closeErr
		}
	}()

	return write(f)
}

func writeEvents(w io.Writer, svc *calendar.Service, now time.Time, backDays, forwardDays int) error {
	return svc.Events.List(primaryCalendarID).
		SingleEvents(true).
		TimeMin(now.AddDate(0, 0, -backDays).Format(time.RFC3339)).
		TimeMax(now.AddDate(0, 0, forwardDays).Format(time.RFC3339)).
		Pages(context.Background(), func(events *calendar.Events) error {
			for _, event := range events.Items {
				if !relevantEvent(event) {
					continue
				}
				output, err := eventToOrg(event, now)
				if err != nil {
					return err
				}
				if _, err := io.WriteString(w, output); err != nil {
					return err
				}
				if _, err := io.WriteString(w, "\n"); err != nil {
					return err
				}
			}
			return nil
		})
}

func selfFor(event *calendar.Event) *calendar.EventAttendee {
	for _, attendee := range event.Attendees {
		if attendee.Self {
			return attendee
		}
	}
	return nil
}

func optionalEvent(self *calendar.EventAttendee) string {
	if self != nil && self.Optional {
		return "❓"
	}
	return ""
}

var (
	roomPrefixRE = regexp.MustCompile(`^[^-]*-[^-]*-`)
	roomSuffixRE = regexp.MustCompile(` +\(.*$`)
	collabRE     = regexp.MustCompile(`Collab Studio - `)
)

func roomEvent(event *calendar.Event) string {
	for _, attendee := range event.Attendees {
		if attendee.Resource && (attendee.ResponseStatus == "accepted") &&
			strings.HasPrefix(attendee.DisplayName, roomDisplayPrefix) {
			output := roomPrefixRE.ReplaceAllString(attendee.DisplayName, "")
			output = roomSuffixRE.ReplaceAllString(output, "")
			output = collabRE.ReplaceAllString(output, "")
			return "/" + output + "/"
		}
	}
	return "💻"
}

func warningEvent(event *calendar.Event, self *calendar.EventAttendee, eventEnd, now time.Time) string {
	if eventEnd.Before(now) {
		return ""
	}

	if len(event.Attendees) == 1 && event.Attendees[0].Self {
		return ""
	}

	if self != nil && self.ResponseStatus == "needsAction" {
		return "⚠️⚠️"
	}

	for _, attendee := range event.Attendees {
		if !attendee.Self && !attendee.Resource && attendee.ResponseStatus == "accepted" {
			return ""
		}
	}
	return "⚠️"
}

func eventToOrg(event *calendar.Event, now time.Time) (string, error) {
	startDateTime, err := time.Parse(time.RFC3339, event.Start.DateTime)
	if err != nil {
		return "", fmt.Errorf("parse event start time: %w", err)
	}
	startDate := startDateTime.Format(dateLayout)
	startTime := startDateTime.Format(timeLayout)

	endDateTime, err := time.Parse(time.RFC3339, event.End.DateTime)
	if err != nil {
		return "", fmt.Errorf("parse event end time: %w", err)
	}
	endTime := endDateTime.Format(timeLayout)
	self := selfFor(event)

	return fmt.Sprintf("** %s%s [[%s][%s]] %s %s-%s <%s>\n", optionalEvent(self), warningEvent(event, self, endDateTime, now), event.HtmlLink, event.Summary, roomEvent(event), startTime, endTime, startDate), nil
}

func relevantEvent(event *calendar.Event) bool {
	self := selfFor(event)
	if self == nil ||
		event.Status == "cancelled" ||
		event.Summary == "" ||
		event.Start.DateTime == "" ||
		len(event.Attendees) == 0 {
		return false
	}

	if self.ResponseStatus == "tentative" || self.ResponseStatus == "declined" {
		return false
	}

	return true
}
