package main

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/gob"
	"errors"
	"flag"
	"fmt"
	"hash/fnv"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	"google.golang.org/api/calendar/v3"
	"google.golang.org/api/option"
)

const (
	defaultBackDays    = 720
	defaultForwardDays = 365
	defaultStoreDir    = "$HOME/.local/share/gcal-to-org"
	primaryCalendarID  = "primary"
	orgHeader          = `
* Google Calendar: primary
These entries have been automatically generated, do not edit this file!
`
	dateLayout        = "2006-01-02 Mon"
	timeLayout        = "15:04"
	roomDisplayPrefix = "SYD 363 George St-"
)

type options struct {
	backDays    int
	forwardDays int
	storeDir    string
}

func main() {
	if err := run(); err != nil {
		if errors.Is(err, errUsage) {
			os.Exit(2)
		}
		log.Fatal(err)
	}
}

func run() error {
	opts, outputPath, err := parseArgs(os.Args[1:])
	if err != nil {
		return err
	}

	store, err := storeDir(opts.storeDir)
	if err != nil {
		return fmt.Errorf("create store directory %q: %w", opts.storeDir, err)
	}

	config := &oauth2.Config{
		ClientID:     MY_CLIENT_ID,
		ClientSecret: MY_CLIENT_SECRET,
		Endpoint:     google.Endpoint,
		Scopes:       []string{calendar.CalendarScope},
	}

	ctx := context.Background()
	client, err := newOAuthClient(ctx, config, store)
	if err != nil {
		return fmt.Errorf("create OAuth client: %w", err)
	}

	svc, err := calendar.NewService(ctx, option.WithHTTPClient(client))
	if err != nil {
		return fmt.Errorf("create Calendar service: %w", err)
	}

	now := time.Now()
	return writeOutputFile(outputPath, func(w io.Writer) error {
		if _, err := io.WriteString(w, orgHeader); err != nil {
			return err
		}

		return writeEvents(w, svc, now, opts.backDays, opts.forwardDays)
	})
}

func parseArgs(args []string) (options, string, error) {
	opts := options{}

	fs := flag.NewFlagSet(filepath.Base(os.Args[0]), flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	fs.IntVar(&opts.backDays, "backDays", defaultBackDays, "How many days back to process events")
	fs.IntVar(&opts.forwardDays, "forwardDays", defaultForwardDays, "How many days forward to process events")
	fs.StringVar(&opts.storeDir, "store", defaultStoreDir, "Directory to store tokens")
	fs.Usage = func() {
		fmt.Fprintf(fs.Output(), "Usage: %s [flags] FILE\n", fs.Name())
		fs.PrintDefaults()
	}

	if err := fs.Parse(args); err != nil {
		return options{}, "", errUsage
	}
	if fs.NArg() != 1 {
		fs.Usage()
		return options{}, "", errUsage
	}

	return opts, fs.Arg(0), nil
}

func writeOutputFile(path string, write func(io.Writer) error) (err error) {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := f.Close(); err == nil && closeErr != nil {
			err = closeErr
		}
	}()

	return write(f)
}

func writeEvents(w io.Writer, svc *calendar.Service, now time.Time, backDays, forwardDays int) error {
	return svc.Events.List(primaryCalendarID).
		SingleEvents(true).
		TimeMin(now.AddDate(0, 0, -backDays).Format(time.RFC3339)).
		TimeMax(now.AddDate(0, 0, forwardDays).Format(time.RFC3339)).
		Pages(context.Background(), func(events *calendar.Events) error {
			for _, event := range events.Items {
				if !relevantEvent(event) {
					continue
				}
				output, err := eventToOrg(event, now)
				if err != nil {
					return err
				}
				if _, err := io.WriteString(w, output); err != nil {
					return err
				}
				if _, err := io.WriteString(w, "\n"); err != nil {
					return err
				}
			}
			return nil
		})
}

var errUsage = errors.New("invalid arguments")

func selfFor(event *calendar.Event) *calendar.EventAttendee {
	for _, attendee := range event.Attendees {
		if attendee.Self {
			return attendee
		}
	}
	return nil
}

func optionalEvent(self *calendar.EventAttendee) string {
	if self != nil && self.Optional {
		return "❓"
	}
	return ""
}

var (
	roomPrefixRE = regexp.MustCompile(`^[^-]*-[^-]*-`)
	roomSuffixRE = regexp.MustCompile(` +\(.*$`)
	collabRE     = regexp.MustCompile(`Collab Studio - `)
)

// Flag if a room is listed in the attendees
func roomEvent(event *calendar.Event) string {
	for _, attendee := range event.Attendees {
		if attendee.Resource && (attendee.ResponseStatus == "accepted") &&
			strings.HasPrefix(attendee.DisplayName, roomDisplayPrefix) {
			output := roomPrefixRE.ReplaceAllString(attendee.DisplayName, "")
			output = roomSuffixRE.ReplaceAllString(output, "")
			output = collabRE.ReplaceAllString(output, "")
			return "/" + output + "/"
		}
	}
	return "💻"
}

// Warning if I am the only person attending.
func warningEvent(event *calendar.Event, self *calendar.EventAttendee, eventEnd, now time.Time) string {
	if eventEnd.Before(now) {
		return ""
	}

	// Handle events where it's just me
	if len(event.Attendees) == 1 && event.Attendees[0].Self {
		return ""
	}

	if self != nil && self.ResponseStatus == "needsAction" {
		return "⚠️⚠️" // I need to action it
	}

	for _, attendee := range event.Attendees {
		if !attendee.Self && !attendee.Resource && attendee.ResponseStatus == "accepted" { // someone is going
			return ""
		}
	}
	return "⚠️"
}

func eventToOrg(event *calendar.Event, now time.Time) (string, error) {
	startDateTime, err := time.Parse(time.RFC3339, event.Start.DateTime)
	if err != nil {
		return "", fmt.Errorf("parse event start time: %w", err)
	}
	startDate := startDateTime.Format(dateLayout)
	startTime := startDateTime.Format(timeLayout)

	endDateTime, err := time.Parse(time.RFC3339, event.End.DateTime)
	if err != nil {
		return "", fmt.Errorf("parse event end time: %w", err)
	}
	endTime := endDateTime.Format(timeLayout)
	self := selfFor(event)

	return fmt.Sprintf("** %s%s [[%s][%s]] %s %s-%s <%s>\n", optionalEvent(self), warningEvent(event, self, endDateTime, now), event.HtmlLink, event.Summary, roomEvent(event), startTime, endTime, startDate), nil
}

func relevantEvent(event *calendar.Event) bool {
	self := selfFor(event)
	if self == nil ||
		event.Status == "cancelled" ||
		event.Summary == "" ||
		event.Start.DateTime == "" ||
		len(event.Attendees) == 0 {
		return false
	}

	if self.ResponseStatus == "tentative" || self.ResponseStatus == "declined" {
		return false
	}

	return true
}

func storeDir(unexpanded string) (string, error) {
	expanded := os.ExpandEnv(unexpanded)
	err := os.MkdirAll(expanded, 0700)
	if err != nil {
		return "", err
	}
	return expanded, nil
}

func newOAuthClient(ctx context.Context, config *oauth2.Config, storeDir string) (*http.Client, error) {
	cacheFile := tokenCacheFile(config, storeDir)
	token, err := tokenFromFile(cacheFile)
	if err != nil {
		token, err = tokenFromWeb(ctx, config)
		if err != nil {
			return nil, err
		}
		if err := saveToken(cacheFile, token); err != nil {
			log.Printf("Warning: failed to cache oauth token: %v", err)
		}
	}

	return config.Client(ctx, token), nil
}

func tokenCacheFile(config *oauth2.Config, storeDir string) string {
	hash := fnv.New32a()
	_, _ = hash.Write([]byte(config.ClientID))
	_, _ = hash.Write([]byte(config.ClientSecret))
	_, _ = hash.Write([]byte(strings.Join(config.Scopes, " ")))
	fn := fmt.Sprintf("gcal-to-org-tok%v", hash.Sum32())
	return filepath.Join(storeDir, url.QueryEscape(fn))
}

func tokenFromFile(file string) (*oauth2.Token, error) {
	f, err := os.Open(file)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	t := new(oauth2.Token)
	err = gob.NewDecoder(f).Decode(t)
	return t, err
}

func tokenFromWeb(ctx context.Context, config *oauth2.Config) (*oauth2.Token, error) {
	ch := make(chan string)
	randState, err := randomState()
	if err != nil {
		return nil, err
	}
	ts := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		if req.URL.Path == "/favicon.ico" {
			http.Error(rw, "", 404)
			return
		}
		if req.FormValue("state") != randState {
			log.Printf("State doesn't match: req = %#v", req)
			http.Error(rw, "", 500)
			return
		}
		if code := req.FormValue("code"); code != "" {
			fmt.Fprintf(rw, "<h1>Success</h1>Authorized.")
			rw.(http.Flusher).Flush()
			ch <- code
			return
		}
		log.Printf("no code")
		http.Error(rw, "", 500)
	}))
	defer ts.Close()

	cfg := *config
	cfg.RedirectURL = ts.URL
	authURL := cfg.AuthCodeURL(randState)
	go openURL(authURL)
	log.Printf("Authorize this app at: %s", authURL)
	code := <-ch
	log.Printf("Got code: %s", code)

	token, err := cfg.Exchange(ctx, code)
	if err != nil {
		return nil, fmt.Errorf("exchange token: %w", err)
	}
	return token, nil
}

func randomState() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

func openURL(url string) {
	try := []string{"xdg-open", "google-chrome", "open"}
	for _, bin := range try {
		err := exec.Command(bin, url).Run()
		if err == nil {
			return
		}
	}
	log.Printf("Error opening URL in browser.")
}

func saveToken(file string, token *oauth2.Token) (err error) {
	f, err := os.Create(file)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := f.Close(); err == nil && closeErr != nil {
			err = closeErr
		}
	}()
	if err := gob.NewEncoder(f).Encode(token); err != nil {
		return err
	}
	return nil
}
